p 'Inspiring post.rb'

post = 'Hey man. I am so sorry to hear you are going through this. I completely understand and relate to exactly what you are going through. I was there, in the pits of hell, 2 years ago. Suicidal depressed, symptoms were debilitating and severe, literally every facet of my life was impacted. I want you to listen to me now, this is temporary, the body can and will heal, you will get better, you will get through this. You need to stay strong. I am speaking from experience, how you feel now is the worst of it, recovery is slow & takes time, but if you follow what I’m about to tell you, your body will begin to heal and you will be on the path to recovery.
I would suggest you copy this comment and leave this forum and any other recovery forum. Do your best to avoid researching this stuff as it will only fuel your anxiety and depression. Here’s the path I would suggest you take to recover.
Based on my experience and research, going on HCG for an extended period, 3 months minimum, can be highly beneficial to restart the HPTA, StAR and neurosteroid cascade. Something I would suggest you look into and consider. Everyone is different though so proceed with caution and at your own risk. Obviously do your own research first and make an informed educated decision.
Mindset: I strongly believe my body has the ability to heal itself. The body has evolved over millions of years, surviving generation after generation through the most dire circumstances. The body has such incredible intelligence. It’s working every day to achieve optimum health. There is no doctor that is as intelligent as my body. It’s job is to maintain health. My body is fantastic, it is amazing, I am occupying my body, it wants to heal, it wants to be healthy, and I have to help it.
Sleep: Focus on good high quality sleep every single night without fail. Sleep is the #1 priority in my recovery protocol. The body heals itself when we sleep. Two hours before bed eliminate artificial light and stimualtion from computers, TV, phones, etc… Spend time focusing on meditation and relaxation. Aim to sleep at 9.00-9.30PM - the time you fall asleep is more important than how long you sleep. Listen to Shawn Stevensons podcast with Richroll for more information. Sleep is the MOST important thing for recovery. You could do everything else I’ve listed here, but without good high quality sleep every night, you will not recover. I also have a sunrise mimicking alarm clock and get 15-30minutes of sunlight first thing in the morning to strengthen the circadian rhythm.
Diet: Strictly avoid all inflammatory foods. No gluten, dairy, refined processed foods, take-away, refined oils, vegetable oils, refined sugar, etc. Limit intake of pro-inflammatory omega 6 fatty acids, increase intake of omega 3s. Eat a wide variety of plants and fiber to optimize gut health and build a strong gut microbiome. Lots of whole plant food - fruits, vegetables, potato, beans, whole grains etc. Consume wild caught fish and grass fed beef. Eating at maintenance or in a calorie surplus. No cheat meals.
Stress + Stimulation: Eliminate all stress and focus on staying calm & relaxed. Meditate and practice deep breathing daily. Spend time out in nature. Significantly reduce stimulation in the form of phone, computer & TV. Avoid violent movies & computer games. Focus on being in that calm, relaxed, parasympathetic state as much as possible. This is the state our body heals in. Practice mindfulness. Meditate daily.
Psychology: Positive and optimisic outlook. The mind is more powerful than any drug out there. You need to understand that you will recover, you need to believe that you will recover, you need to put your mind to it and truly believe that you will recover. Always chose to be optimistic and positive about everything. Realise that this is temporary. This is an opportunity for growth & development. You will be so much stronger after this experience. Always chose to be positive.
Gratefulness & Gratitude: Reminding myself every day what I am grateful for in my life. I truly believe I am lucky even though I have PFS. My life could have been so much worse. I could have been born in Syria and beheaded by ISIS. Or born in Africa and starved to death at 3 years old. Or slaughtered by machine gun fire on the front wave of the D Day landings. I could be paraplegic and be bedridden for the rest of my life. I will always chose to be grateful and positive for everything in my life, it could have been so much worse. I will not compare myself to my friends or other people I see on social media, instead I will be grateful for what I do have. This is an opportunity for transformation, I think of all the positives that will come from my situation, I will be able to appreciate the smaller things in life so much more once recovered, I always chose to be positive with everything in life.
Exercise: It’s very important that you don’t push yourself to exercise. If you feel worse after exercising, do not fucking do it, there’s a reason you feel worse and your body is trying to tell you that. Always listen to your body. Exercise can create a lot of inflammation and stress when your body is in a weak burdened state. I do believe walking daily can be very beneficial. Especially walks and hikes out in nature, being mindful and off the phone & technology. If you want to do exercise just walk. Walk barefoot on grass. Walk in nature. And always listen to your body.
Motivation & Information: I highly recommend the Youtube channel Health Recovery. James who runs the channel, spent I believe 8 years of his life suffering with severe chronic illness and recovered his health naturally through trial and error. I made the most ground with my recovery when I started listening to and following his advice. I personally have downloaded every single one of his videos (using J Downloader) and listen when I’m bored on my iPod. He gives fantastic information for our situation and is a really great source of motivation.'

p post.length