name: Build EPA ECHO data

on:
  schedule:
    - cron: '12 10 * * *'   # daily ~10:12 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Optional: quick probe of the CSV endpoint
      - name: Probe ECHO endpoint (debug only)
        run: |
          echo "Testing ECHO CSV endpoint headers:"
          curl -I -A "$FETCH_UA" "$ECHO_URL" || true
        env:
          # 🔁 Set this to a real, downloadable ECHO CSV URL (see notes below)
          ECHO_URL: https://r.jina.ai/http://example.com/your-echo-export.csv
          FETCH_UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 (GitHubActionsBot)

      - name: Build ECHO JSON
        env:
          # 🔁 Set this to a real, downloadable ECHO CSV URL
          ECHO_URL: https://echo.epa.gov/files/data/Data_Download_ECHO_10_12_2025_68ec51310a9e4.csv

          # Filters
          STATE: ALL          # use 'ALL' for all states
          DAYS: '365'        # lookback days for “recent” events

          # network / header tuning
          FETCH_UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 (GitHubActionsBot)
          FETCH_RETRIES: '4'
          FETCH_BACKOFF_MS: '750'
        run: node scripts/build-echo-data.mjs

      - name: Verify outputs exist
        run: |
          set -e
          echo "Top-level:" && ls -la
          echo "data/:" && ls -la data || echo "(no data directory)"
          echo "Search for files:" && find . -maxdepth 4 -type f -name 'epa-*.json' -print || true
          if [ ! -f data/epa-incidents.json ] || [ ! -f data/epa-summary.json ]; then
            echo "::error::Expected files not found at data/epa-incidents.json and/or data/epa-summary.json"
            exit 1
          fi

      - name: Commit data files (only if present)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -f data/epa-*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(data): update EPA ECHO JSON"
            git push
          fi
