name: Build OSHA data


on:
schedule:
- cron: "12 10 * * *" # daily ~10:12 UTC (adjust)
workflow_dispatch: {}


jobs:
build:
runs-on: ubuntu-latest
permissions:
contents: write # to commit JSON back to repo
steps:
  - uses: actions/checkout@v4
  with:
    persist-credentials: true


- name: Use Node 20
uses: actions/setup-node@v4
with:
node-version: '20'


- name: Build OSHA JSON
env:
STATE: WI # change to ALL or another state if you like
DAYS: 90
# Optional LLM settings (uncomment if you want AI summary)
# OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
# LLM_MODEL: gpt-4o-mini
# LLM_API_URL: https://api.openai.com/v1/chat/completions
run: node scripts/build-osha-data.mjs


- name: Commit data files
run: |
if [[ -n $(git status --porcelain) ]]; then
git config user.name "github-actions"
git config user.email "actions@users.noreply.github.com"
git add data/osha-*.json
git commit -m "chore(data): update OSHA SIR JSON" || echo "No changes"
git push
else
echo "No data changes to commit"
fi
