name: Build OSHA data

on:
  schedule:
    - cron: '12 10 * * *'   # daily ~10:12 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow committing JSON back to repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build OSHA JSON
        env:
          STATE: WI
          DAYS: '90'
          # Optional LLM settings:
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # LLM_MODEL: gpt-4o-mini
          # LLM_API_URL: https://api.openai.com/v1/chat/completions
        run: node scripts/build-osha-data.mjs

      - name: Commit data files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/osha-*.json || true
          git diff --cached --quiet && echo "No changes" || git commit -m "chore(data): update OSHA SIR JSON"
          git push
