name: Daily GPT Update # Name of your workflow

on:
  schedule:
    # This cron expression means "at 13:00 UTC every day".
    # 13:00 UTC is 8:00 AM CST/CDT (Racine, Wisconsin timezone).
    - cron: '0 13 * * *'
  workflow_dispatch: # Allows you to manually run the workflow from the GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest # The type of runner to use for the job
    permissions:
      contents: write # CRITICAL: This grants the workflow the necessary permissions to push commits to your repository.

    steps:
      - name: Checkout repository code # Step 1: Get your repository's code onto the runner
        uses: actions/checkout@v4 # Recommended to use the latest stable version of the checkout action

      - name: Set up Node.js environment # Step 2: Prepare the Node.js environment
        uses: actions/setup-node@v4 # Recommended to use the latest stable version of the Node.js setup action
        with:
          node-version: '18' # Specify the Node.js version your update.js script needs

      - name: Install Node.js dependencies # Step 3: Install packages like 'openai' and 'dotenv'
        # This command will look for a package.json file in your repo's root
        run: npm install

      - name: Run update script to generate content # Step 4: Execute your script
        # This script calls the OpenAI API and writes the result to historical-news.html
        run: node update.js
        env:
          # Passes the OPENAI_API_KEY from your GitHub Secrets to the Node.js script's environment
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Configure Git for automated push # Step 5: Set up Git user for the commit
        run: |
          # Use the special 'github-actions[bot]' user for automated commits
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes # Step 6: Stage, commit, pull, and push
        run: |
          # 6a. Stage all changes made by the update.js script
          git add .

          # 6b. Commit the changes. '|| true' ensures the step doesn't fail if no changes were made (i.e., nothing to commit).
          git commit -m "Automated: Update ChatGPT daily report" || true

          # 6c. Pull the latest from the remote branch and rebase your local commits on top.
          # This is essential to prevent "Updates were rejected" errors if the remote branch
          # has new commits that occurred after this workflow started.
          # IMPORTANT: Change 'master' to 'main' if your default branch is 'main'.
          git pull --rebase origin master

          # 6d. Finally, push your changes.
          # The 'GITHUB_TOKEN' (enabled by 'permissions: contents: write' above) is used for authentication.
          git push